###
# 유저 생성 signup
POST http://localhost:3000/api/sign-up HTTP/1.1
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "testpassword",
  "passwordConfirm": "testpassword",
  "name": "testname"
}

### 
# @name login
POST http://localhost:3000/api/sign-in HTTP/1.1
Content-Type: application/json

{
  "email": "test@email.com",
  "password": "testpassword"
}

###
# @name getUserInfo
GET http://localhost:3000/api/users/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjYsImlhdCI6MTcwMjI1MTQ3OCwiZXhwIjoxNzAyMjk0Njc4fQ.8qb_dcGnthv5IvwmFUnnERx7ypMvN1zOZf2SU5F1MuM